Jarate Rage removal bugfix
Starblaster64/Vs-Saxton-Hale-2 pull request #178
Opened 2021-07-02 20:36 UTC by OpbCodez

Contains the debug attempt to fix CBS and (on skial, Gentlespy ambassador) head shot's passing through demo and sniper shields but not much progress there.
Jarate rage removal fixed through some adjustments to the logic and the trigger behind it. Tested on a private server and works correctly.

2021-07-03 19:58 UTC, assyrianic commented on addons/sourcemod/scripting/modules/handler.sp
> +public void IsBossJarated(const BaseBoss player)		///PATCH: Attempted slight rework of jarate rage removal code (working 2/7/21)
change name to `ManageBossJarate`.

2021-07-06 15:48 UTC, assyrianic commented
this has conflicts via FF2 code.

2021-07-12 18:52 UTC, OpbCodez commented
I have redone the Jarate code and adjusted some other segments of code.

Hales will have their rage removed when they take damage while they are under the Jarate condition. Similar to the gas passer mechanic.

2021-07-12 22:53 UTC, 01Pollux requested changes
Shouldn't you be passing victim then the attacker uid for `Call_OnBossJarated` according to vsh2 API? also you might aswell be using `BaseBoss` instead of `int&`.

2021-07-13 07:11 UTC, DatOpb commented
I had to use int& attacker as the function above it does not use `BaseBoss` instead uses `int&.`. It caused an error/warning when I tried using `const BaseBoss Attacker`.
I can swap the values for the `Call_OnBossJarated` later today though.

2021-07-13 08:07 UTC, 01Pollux commented
Another thing, there is a mismatch while trying to call `ManageBossJarated`, the one in `handler.sp` is using attacker index, while the other one in `event.sp` is using attacker client-userid.

2021-07-13 10:32 UTC, OpbCodez commented
Ill take a look and update accordingly to fix that

2021-07-13 17:54 UTC, OpbCodez commented
I've adjusted what I can, but I can't use `BaseBoss attacker` with the parent codes current input variables.

2021-07-13 19:47 UTC, 01Pollux commented on addons/sourcemod/scripting/modules/forwards.sp
> +		Call_PushCell(victim);
What i meant by passing victim then attacker is actually here, the parameter in vsh2.inc is `function [void, Action](const VSH2Player victim, const VSH2Player attacker);`. So you should have just swapped the position of `Call_PushCell` instead of making it hard for yourself

2021-07-13 19:54 UTC, OpbCodez commented on addons/sourcemod/scripting/modules/forwards.sp
> +		Call_PushCell(victim);
Lol I forgot about that, but there's nothing wrong in doing some things the hard way every once in a while.

2021-07-13 21:08 UTC, 01Pollux commented on addons/sourcemod/scripting/modules/forwards.sp
> +		Call_PushCell(victim);
Unfortunately, that still hasn't solve the problem, you are still passing the wrong parameters (victim first, then the attacker)

2021-07-18 01:39 UTC, closed without merging